# This means the file is a yaml file
---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    # This has docker-compose, docker ready
    runs-on: ubuntu-20.04
    steps:
      # steps will executed in order
      - name: Login to Docker Hub
        # Use existing action in Github action
        uses: docker/login-action@v1
        # Passing parameters
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
